name: Lints

on:
  push:
    branches: [ $default-branch ]
    tags:
      - v*.*.*
  pull_request:

defaults:
  run:
    shell: bash

env:
  TERM: dumb

jobs:
  eslint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
          
      - run: echo $PWD
        
      - name: Bootstrapping
        run: ./.github/scripts/boostrap.sh

      - name: ESLint
        run: ./.github/scripts/lint.sh
  typescript:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Types
        run: yarn check-type
    
    
    # - uses: actions/setup-node@v3
    #   with:
    #     node-version: '16'
    #     cache: 'npm'
    #     cache-dependency-path: script/validate-data/package-lock.json
